<a href="https://colab.research.google.com/github/Sak-shi437/linear_regression/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simple Linear Regression

- Topics Covered:
    1. Loading Dataset
    2. Implementing Various Operations

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

---
#### Loading Dataset

In [27]:
df = pd.read_csv("House Price Prediction Dataset.csv")
df.head(2)

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998

---
#### Implenting Various Operations

In [28]:
df["Location"].unique()

array(['Downtown', 'Suburban', 'Urban', 'Rural'], dtype=object)

In [21]:
df.shape

(2000, 10)

In [ ]:
df.info()

In [ ]:
df.describe()

In [6]:
df.isnull().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.dtypes

Id            int64
Area          int64
Bedrooms      int64
Bathrooms     int64
Floors        int64
YearBuilt     int64
Location     object
Condition    object
Garage       object
Price         int64
dtype: object

In [29]:
df.drop("Id",axis=1,inplace=True)

In [23]:
df.head()

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3592,2,2,3,1938,Downtown,Good,No,266746
3,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,4926,1,4,2,1975,Downtown,Fair,Yes,636056

---
#### Operation on Column :Garage"

In [10]:
df["Garage"].unique()

array(['No', 'Yes'], dtype=object)

In [30]:
df["Garage"] = df["Garage"].map({
    "Yes":1,
    "No" : 0
})

In [12]:
df.head()

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1360,5,4,3,1970,Downtown,Excellent,0,149919
1,4272,5,4,3,1958,Downtown,Excellent,0,424998
2,3592,2,2,3,1938,Downtown,Good,0,266746
3,966,4,2,2,1902,Suburban,Fair,1,244020
4,4926,1,4,2,1975,Downtown,Fair,1,636056

---
#### Operation on Columns: "Location", "Condition"

In [31]:
# One-Hot Encode Location and Condition

df = pd.get_dummies(
    df,
    columns=["Location", "Condition"],
    drop_first=True
)

In [ ]:
df.head()

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Garage,Price,Location_Rural,Location_Suburban,Location_Urban,Condition_Fair,Condition_Good,Condition_Poor
0,1360,5,4,3,1970,No,149919,False,False,False,False,False,False
1,4272,5,4,3,1958,No,424998,False,False,False,False,False,False
2,3592,2,2,3,1938,No,266746,False,False,False,False,True,False
3,966,4,2,2,1902,Yes,244020,False,True,False,True,False,False
4,4926,1,4,2,1975,Yes,636056,False,False,False,True,False,False

In [32]:
# Converting Datatype to int

df["Location_Rural"] = df["Location_Rural"].astype(int)
df["Location_Suburban"] = df["Location_Suburban"].astype(int)
df["Location_Urban"] = df["Location_Urban"].astype(int)
df["Condition_Fair"] = df["Condition_Fair"].astype(int)
df["Condition_Good"] = df["Condition_Good"].astype(int)
df["Condition_Poor"] = df["Condition_Poor"].astype(int)

df.head()

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Garage,Price,Location_Rural,Location_Suburban,Location_Urban,Condition_Fair,Condition_Good,Condition_Poor
0,1360,5,4,3,1970,0,149919,0,0,0,0,0,0
1,4272,5,4,3,1958,0,424998,0,0,0,0,0,0
2,3592,2,2,3,1938,0,266746,0,0,0,0,1,0
3,966,4,2,2,1902,1,244020,0,1,0,1,0,0
4,4926,1,4,2,1975,1,636056,0,0,0,1,0,0

---
#### Operation on Column: 'Price'

In [35]:
X = df.drop("Price", axis=1)
y = df["Price"]

---
#### Train Test Split

In [33]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train,y_train)

In [ ]:
X_test

In [ ]:
y_test

In [ ]:
lr.predict(X_test.iloc[[0]])

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.show()

In [ ]:
X = df[['Area']]
y = df['Price']

In [ ]:
plt.scatter(df['Area'], df['Price'])
plt.plot(X_train, lr.predict(X_train), color='red')
plt.xlabel("Area")
plt.ylabel("Price")
plt.show()

In [ ]:
m = lr.coef_

In [ ]:
b = lr.intercept_

In [ ]:
m * 8.58 + b

In [ ]:
print("Train Score:", lr.score(X_train, y_train))
print("Test Score:", lr.score(X_test, y_test))

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = lr.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred)**0.5)
print("R2:", r2_score(y_test, y_pred))